name: a_and_p_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flask
  - pip
  - pip:
      - transformers
      - torch
      - PyMuPDF
      - Pillow
      - scikit-learn
